monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.usb-FIIO_FiiO_K11_R2R-01" }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = false
      }
    }
  }
]
