monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.usb-FIIO_FiiO_K11_R2R-01.playback.0.0" }
    ]
    actions = {
      update-props = {
        audio.format = "S32LE"
        audio.allowed-rates = "44100,48000,88200,96000,176400,192000,352800,384000"
        node.max-latency = 0
        api.alsa.period-size = 128
        api.alsa.headroom = 128
      }
    }
  }
]
