-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    input = {
        accel_profile = "flat",
    },
    misc = {
        vrr = 3,
    },
})

-- Monitors
hl.monitor({
    output = "desc:AOC Q27G41ZDF RK2S3UA000087",
    disabled = false,
    mode = "2560x1440@240.00Hz",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    vrr = 3,
    cm = "srgb",
})
