color0 #5c4039
color1 #ffb4ab
color2 #ffb4a2
color3 #ffb4a2
color4 #ebc155
color5 #ffb4a2
color6 #ffb4a2
color7 #fbdcd4
color8 #ac8980
color9 #ffb4ab
color10 #ffb4a2
color11 #ffb4a2
color12 #ebc155
color13 #ffb4a2
color14 #ffb4a2
color15 #fbdcd4

cursor                #fbdcd4
cursor_text_color     #000000
background            #000000
foreground            #fbdcd4
selection_foreground  #e5beb4
selection_background  #5c4039
active_border_color   #ffb4a2
inactive_border_color #4d332c
url_color             #ffb4a2

active_tab_foreground   #611200
active_tab_background   #ffb4a2
inactive_tab_foreground #e5beb4
inactive_tab_background #4d332c
cursor_trail_color      #e5beb4
