color0 #5f3f3a
color1 #ffb4ab
color2 #ffb4a9
color3 #ffb4a9
color4 #fdba57
color5 #ffb4a9
color6 #ffb4a9
color7 #ffdad5
color8 #af8781
color9 #ffb4ab
color10 #ffb4a9
color11 #ffb4a9
color12 #fdba57
color13 #ffb4a9
color14 #ffb4a9
color15 #ffdad5

cursor                #ffdad5
cursor_text_color     #000000
background            #000000
foreground            #ffdad5
selection_foreground  #e9bcb5
selection_background  #5f3f3a
active_border_color   #ffb4a9
inactive_border_color #50322d
url_color             #ffb4a9

active_tab_foreground   #690001
active_tab_background   #ffb4a9
inactive_tab_foreground #e9bcb5
inactive_tab_background #50322d
cursor_trail_color      #e9bcb5
